[0m11:43:23.554114 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1083ba0c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107da48f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107da64e0>]}


============================== 11:43:23.556996 | 73fff47f-f5ff-4c01-a9f9-dc480e25296a ==============================
[0m11:43:23.556996 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:43:23.557346 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/joshuaward/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init f1_duckdb_project', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:43:23.566821 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m11:43:23.571706 [info ] [MainThread]: 
Your new dbt project "f1_duckdb_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:43:23.572008 [info ] [MainThread]: Setting up your profile.
[0m11:43:25.700080 [info ] [MainThread]: Profile f1_duckdb_project written to /Users/joshuaward/.dbt/profiles.yml using target's sample configuration. Once updated, you'll be able to start developing with dbt.
[0m11:43:25.701914 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 2.1891868, "process_in_blocks": "0", "process_kernel_time": 0.140381, "process_mem_max_rss": "102727680", "process_out_blocks": "0", "process_user_time": 0.708215}
[0m11:43:25.702325 [debug] [MainThread]: Command `dbt init` succeeded at 11:43:25.702252 after 2.19 seconds
[0m11:43:25.702608 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088cf950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10498c440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108578b60>]}
[0m11:43:25.702893 [debug] [MainThread]: Flushing usage events
[0m11:43:26.195721 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:46:32.452452 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bd5e80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085be450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085be3c0>]}


============================== 11:46:32.455737 | 6b6a22b8-0956-4f83-a04e-1debca94bacb ==============================
[0m11:46:32.455737 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:46:32.456096 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': '/Users/joshuaward/.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:46:32.456421 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/joshuaward/Documents/Data-Engineering/F1Project/F1Project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:46:32.457861 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.050339043, "process_in_blocks": "0", "process_kernel_time": 0.125212, "process_mem_max_rss": "99483648", "process_out_blocks": "0", "process_user_time": 0.654006}
[0m11:46:32.458272 [debug] [MainThread]: Command `dbt run` failed at 11:46:32.458213 after 0.05 seconds
[0m11:46:32.458513 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108d93440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1090e3b60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1090e3bc0>]}
[0m11:46:32.458716 [debug] [MainThread]: Flushing usage events
[0m11:46:32.952696 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:51:59.285982 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104948da0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a33d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a33aa0>]}


============================== 11:51:59.289157 | 39ad5711-8bf1-4649-9987-818f8d4d8583 ==============================
[0m11:51:59.289157 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:51:59.289545 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/joshuaward/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:51:59.289866 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/joshuaward/Documents/Data-Engineering/F1Project/F1Project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:51:59.291165 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05168871, "process_in_blocks": "0", "process_kernel_time": 0.130175, "process_mem_max_rss": "99844096", "process_out_blocks": "0", "process_user_time": 0.655551}
[0m11:51:59.291494 [debug] [MainThread]: Command `dbt run` failed at 11:51:59.291443 after 0.05 seconds
[0m11:51:59.291686 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11009cb00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1103f52b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a33b90>]}
[0m11:51:59.291858 [debug] [MainThread]: Flushing usage events
[0m11:51:59.763998 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:55:49.473866 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108e866c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109393e90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109393bf0>]}


============================== 11:55:49.477112 | 5cff880d-ead8-4f99-8361-14bd702bd384 ==============================
[0m11:55:49.477112 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:55:49.477504 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/joshuaward/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:55:49.477836 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/joshuaward/Documents/Data-Engineering/F1Project/F1Project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:55:49.479170 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.055511165, "process_in_blocks": "0", "process_kernel_time": 0.140803, "process_mem_max_rss": "100384768", "process_out_blocks": "0", "process_user_time": 0.676598}
[0m11:55:49.479594 [debug] [MainThread]: Command `dbt run` failed at 11:55:49.479524 after 0.06 seconds
[0m11:55:49.479826 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109393ec0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109393f80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109393710>]}
[0m11:55:49.480029 [debug] [MainThread]: Flushing usage events
[0m11:55:50.005441 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:05:17.133241 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10660ecc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10640df70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10640e480>]}


============================== 12:05:17.136150 | 08d0dfdf-cdda-488b-99d6-e93434de0209 ==============================
[0m12:05:17.136150 [info ] [MainThread]: Running with dbt=1.9.4
[0m12:05:17.136492 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/joshuaward/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:05:17.136798 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/joshuaward/Documents/Data-Engineering/F1Project/F1Project/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:05:17.138089 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.048302416, "process_in_blocks": "0", "process_kernel_time": 0.141424, "process_mem_max_rss": "97796096", "process_out_blocks": "0", "process_user_time": 0.673116}
[0m12:05:17.138427 [debug] [MainThread]: Command `dbt run` failed at 12:05:17.138372 after 0.05 seconds
[0m12:05:17.138626 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1065a5d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079016d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fb0860>]}
[0m12:05:17.138814 [debug] [MainThread]: Flushing usage events
[0m12:05:17.630868 [debug] [MainThread]: An error was encountered while trying to flush usage events
